[2022-06-03 19:19:19,690] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-03T19:19:12.616653+00:00 [queued]>
[2022-06-03 19:19:19,702] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-03T19:19:12.616653+00:00 [queued]>
[2022-06-03 19:19:19,702] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 19:19:19,703] {taskinstance.py:1358} INFO - Starting attempt 1 of 2
[2022-06-03 19:19:19,703] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 19:19:19,721] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): processing_data> on 2022-06-03 19:19:12.616653+00:00
[2022-06-03 19:19:19,727] {standard_task_runner.py:52} INFO - Started process 174 to run task
[2022-06-03 19:19:19,731] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'processing_data', 'manual__2022-06-03T19:19:12.616653+00:00', '--job-id', '330', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmp3_famfop', '--error-file', '/tmp/tmp8k0rthu2']
[2022-06-03 19:19:19,733] {standard_task_runner.py:80} INFO - Job 330: Subtask processing_data
[2022-06-03 19:19:19,807] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-03T19:19:12.616653+00:00 [running]> on host d31a31117917
[2022-06-03 19:19:20,134] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T19:19:12.616653+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-03T19:19:12.616653+00:00
[2022-06-03 19:19:21,092] {base.py:68} INFO - Using connection ID 's3_conn' for task execution.
[2022-06-03 19:19:21,093] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-06-03 19:19:22,965] {python.py:173} INFO - Done. Returned value was: None
[2022-06-03 19:19:22,980] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=nyc_bus_breakdown_pipeline, task_id=processing_data, execution_date=20220603T191912, start_date=20220603T191919, end_date=20220603T191922
[2022-06-03 19:19:23,038] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-03 19:19:23,066] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
