[2022-06-02 21:47:29,132] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T21:47:23.764497+00:00 [queued]>
[2022-06-02 21:47:29,140] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T21:47:23.764497+00:00 [queued]>
[2022-06-02 21:47:29,141] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 21:47:29,142] {taskinstance.py:1358} INFO - Starting attempt 1 of 2
[2022-06-02 21:47:29,143] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 21:47:29,156] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): processing_data> on 2022-06-02 21:47:23.764497+00:00
[2022-06-02 21:47:29,161] {standard_task_runner.py:52} INFO - Started process 15371 to run task
[2022-06-02 21:47:29,164] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'processing_data', 'manual__2022-06-02T21:47:23.764497+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmpccq9k5v8', '--error-file', '/tmp/tmpoo2j91kx']
[2022-06-02 21:47:29,165] {standard_task_runner.py:80} INFO - Job 15: Subtask processing_data
[2022-06-02 21:47:29,224] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T21:47:23.764497+00:00 [running]> on host 23b8b054d032
[2022-06-02 21:47:29,373] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T21:47:23.764497+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-02T21:47:23.764497+00:00
[2022-06-02 21:47:29,853] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etls/transformations.py", line 69, in processing_data
    df = extract_first_number(df, "how_long_delayed")
  File "/opt/airflow/dags/etls/helpers.py", line 129, in extract_first_number
    df[column] = parallelize_on_rows(df[column], regex_number_finder)
  File "/opt/airflow/dags/etls/helpers.py", line 99, in parallelize_on_rows
    return parallelize(data, partial(run_on_subset, func), num_of_processes)
  File "/opt/airflow/dags/etls/helpers.py", line 87, in parallelize
    pool = Pool(num_of_processes)
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 110, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
[2022-06-02 21:47:29,900] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_bus_breakdown_pipeline, task_id=processing_data, execution_date=20220602T214723, start_date=20220602T214729, end_date=20220602T214729
[2022-06-02 21:47:29,916] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task processing_data (daemonic processes are not allowed to have children; 15371)
[2022-06-02 21:47:29,939] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-02 21:47:29,997] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
