[2022-06-03 18:30:01,506] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-03T18:29:54.050858+00:00 [queued]>
[2022-06-03 18:30:01,517] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-03T18:29:54.050858+00:00 [queued]>
[2022-06-03 18:30:01,517] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 18:30:01,518] {taskinstance.py:1358} INFO - Starting attempt 1 of 2
[2022-06-03 18:30:01,518] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 18:30:01,535] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): processing_data> on 2022-06-03 18:29:54.050858+00:00
[2022-06-03 18:30:01,541] {standard_task_runner.py:52} INFO - Started process 152 to run task
[2022-06-03 18:30:01,546] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'processing_data', 'manual__2022-06-03T18:29:54.050858+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmp21u7p_gf', '--error-file', '/tmp/tmpr_mipanz']
[2022-06-03 18:30:01,547] {standard_task_runner.py:80} INFO - Job 201: Subtask processing_data
[2022-06-03 18:30:01,612] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-03T18:29:54.050858+00:00 [running]> on host f32b03068075
[2022-06-03 18:30:01,871] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T18:29:54.050858+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-03T18:29:54.050858+00:00
[2022-06-03 18:30:02,992] {base.py:68} INFO - Using connection ID 's3_conn' for task execution.
[2022-06-03 18:30:02,994] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-06-03 18:30:04,649] {python.py:173} INFO - Done. Returned value was: None
[2022-06-03 18:30:04,705] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=nyc_bus_breakdown_pipeline, task_id=processing_data, execution_date=20220603T182954, start_date=20220603T183001, end_date=20220603T183004
[2022-06-03 18:30:04,732] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-03 18:30:04,773] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
